(package "eask-api"
         "0.1.0"
         "Eask API")

(website-url "https://github.com/emacs-eask/eask-api")
(keywords "lisp" "eask" "api")

(package-file "eask-api.el")

(files "eask-api-util.el")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
