(package "eask"
         "0.1.0"
         "Core Eask APIs")

(website-url "https://github.com/emacs-eask/eask-api")
(keywords "lisp" "eask" "api")

(package-file "eask.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(files "eask-api.el"
       "eask-api-core.el")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
