name: System

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_BADGES: 'jcs-emacs/badges'

jobs:
  generate_badge:
    runs-on: ubuntu-latest
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: 30.2

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v5

    - name: Generate SVG badges (system)
      run: make generate_badges_system

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges - SYSTEM"
        git push
